sewabus/akun/urls.py
from django.conf.urls import url
from django.urls import path
from akun import views# SET THE NAMESPACE!
app_name = 'akun' # jangan lupa edit bagian ini, esuaikan app yang dibuat

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

sewabus/sewabus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('sewa/', include('sewa.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('login/', LoginView.as_view(), name='masuk'),
    path('keluar/', LogoutView.as_view(next_page='masuk'), name='keluar'),
    path('registration/', include('registration.urls'))
]


# from django.contrib import admin
# from django.urls import path,include
# from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('home.urls')),
#     path('sewa/', include('sewa.urls')),
#     path('pengguna/', include('pengguna.urls')),
#     path('login/', include('login.urls')),

# ]

sewabus/akun/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, blank=True, null=True)
    foto_profil = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

sewabus/akun/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import sewabus
# from .models import UserProfileInfo

def index(request):
    if request.user.is_authenticated:
        dt = UserProfileInfo.objects.filter(user=request.user.id).first()
        data = {
            'bio': dt
        }
        return render(request,'akun/index.html',data)
    # print(dt.foto_profil)
    return render(request,'akun/index.html')

@login_required
def special(request):
    print(user_type)
    return HttpResponse("Berhasil Login !")
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'foto_profil' in request.FILES:
                print('found it')
                profile.foto_profil = request.FILES['foto_profil']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'akun/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'akun/login.html', {})

sewabus/akun/templates/akun/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Register Sederhana | Afrizals Blog</title>
    <!-- Letakkan CSS disini -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django landing page disini#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'akun:register' %}">Register</a></li>     
          {# tambahkan beberapa logika untuk dikembangkan#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'akun:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

sewabus/akun/templates/akun/index.html
{% extends "akun/base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    
    {% if user.is_authenticated %}
    <h1>Selamat datang dihalaman admin!</h1>
        <h2>Hello {{ user.username }}</h2><br>
        <img alt="gambar" class="img" src="media/{{ bio.foto_profil }}" style="width: 100px; height:100px;">
    {% else %}
    <h1>Selamat datang !</h1>
        <h2>Silahkan Login atau Register.</h2>
    {% endif %}
  </div>
</div>{% endblock %}

sewabus/akun/templates/akun/login.html
{% extends 'akun/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1><form method="post" action="{% url 'login:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
  </div>
{% endblock %}

sewabus/akun/templates/akun/register.html
{% extends "login/base.html" %}
{% load static %}{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Terima kasih telah registrasi!</h1>
      {% else %}
        <h1>Register Disini</h1>
        <h3>Silahkan isi form dibawah ini</h3><form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}